version: '3.8'

services:
    postgis:
      image: postgis/postgis
      hostname: postgis
      environment:
        POSTGRES_DB: digantara
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgis
      restart: unless-stopped
      volumes:
          - ../postgres:/var/lib/postgresql/data
      ports:
          - 5432:5432
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-d", "digantara"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
    pgadmin:
      image: dpage/pgadmin4
      ports:
        - "80:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: manans@tutanota.com
        PGADMIN_DEFAULT_PASSWORD: manish
    digantara:
      image: digantara
      volumes:
          - ./Assignment data:/digantara/Assignment data
      depends_on:
        postgis:
          condition: service_healthy
